language: python
python:
  - "2.7"
install:
  - sudo locale-gen pt_BR.UTF-8
  - pip install -r requirements.txt
  - python manage.py -c 'Testing' create_db
script:
  - nosetests
notifications:
  email:
    - tupy@riachao.com
